config/routes.rb
Rails.application.routes.draw do
  get '/jira' => 'jira#index'
  get '/jira/show' => 'jira#show'
  get '/jira/initial_json' => 'jira#initial_json'
  post '/jira/installed' => 'jira#installed'
  post '/jira/uninstalled' => 'jira#uninstalled'

  root 'jira#initial_json'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jwt_token.rb
class JwtToken < ActiveRecord::Base
  

  has_many :jwt_users, dependent: :destroy
end

app/models/jwt_user.rb
class JwtUser < ActiveRecord::Base
  belongs_to :jwt_token

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	include AtlassianJwtAuthentication::Filters
	include AtlassianJwtAuthentication::Helper

	protect_from_forgery with: :null_session

	before_action :on_add_on_installed, only: [:installed]
	before_action :on_add_on_uninstalled, only: [:uninstalled]

	def initial_json
		render 'atlassian-connect.json'
	end

	def installed
	end

	def uninstalled
	end

end

app/controllers/jira_controller.rb
class JiraController < ApplicationController

# will respond with head(:unauthorized) if verification fails
  before_action only: [:index] do |controller|
    controller.send(:verify_jwt, 'app-moc-report')
  end
  before_action :OAuth_access_token, only: [:index, :show]

  def index
    @form_params = Reports::TimeReport.create_form_params(current_jwt_auth.api_base_url, current_jwt_user.oauth_access_token)
  end

  def show
    params['group_by'] = params['group_by'].present? && params['ordered_group_by'].present? ? params['ordered_group_by'].split(',') : ['issue']
    if params['projects'].present?
      params['projects'] = params['projects'].split unless params['projects'].kind_of?(Array)
    end
    @grouping = params['group_by']
    @report_params = report_params
    @api_base_url = current_jwt_auth.api_base_url
    @report =  Reports::TimeReport.create_report(@report_params, @api_base_url, current_jwt_user.oauth_access_token)
    respond_to do |format|
      format.js
      format.csv { send_data Reports::TimeReport.to_csv(@report), filename: 'timelog.csv' }
    end
  end

  private

  def report_params
    params.permit(:from, :to, {projects: []}, {issue_types: []}, {assignees: []}, {statuses: []}, {group_by: []}, :ordered_group_by, :detail_by, :commit)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def style(report_part, type)
    if report_part == 'body'
      if type == 'grouping'
        'string'
      elsif type == 'period'
        'number'
      else
        'bold_number'
      end
    else
      type == 'grouping' ? 'string' : 'number'
    end
  end

  def data_type(i)
    @report['header'][@report['header'].keys[i]]
  end
end

app/helpers/configuration_helper.rb
module ConfigurationHelper
end

app/views/jira/_report.haml
- if @report.present?
  %table.aui
    %thead
      %tr
        - @report['header'].each do |value, type|
          %th{:id => value, :class => style('header', type)}
            = type == 'period' ? value : value.titlecase
    %tbody
      - @report['body'].each do |body_row|
        %tr
          - body_row.each_with_index do |value, i|
            %td{:headers => @report['header'][i], :class => style('body', data_type(i))}
              %p
                - if value.present?
                  - if ['project', 'issue'].include?(@grouping[i])
                    - key = value.split(/:::/).first
                    -#= link_to key, "https://testtost2018:zzz123456789@romand.atlassian.net/browse/#{key}"
                    = link_to key, "#{@api_base_url}/browse/#{key}"
                    = ": #{value.split(/:::/).last}"
                  - elsif @grouping[i] == 'assignee'
                    -#= link_to value, "https://testtost2018:zzz123456789@romand.atlassian.net/secure/ViewProfile.jspa?name=#{value}"
                    = link_to value, "#{@api_base_url}/secure/ViewProfile.jspa?name=#{value}"
                  - else
                    = value
    %tfoot
      %tr.footer
        - @report['footer'].each_with_index do |value, i|
          %td{:id => @report['header'][i], :class => style('footer', data_type(i))}
            = value
      %tr
        = link_to 'Export to csv', jira_show_path(format: :csv, params: @report_params)

app/views/jira/atlassian-connect.json.erb
{
  "name": "MOC Report Plugin",
  "description": "Atlassian Connect MOC Report app",
  "key": "app-moc-report",
  "baseUrl": "https://romand.serveo.net",
  "vendor": {
    "name": "Example, Inc.",
    "url": "http://example.com"
  },
  "authentication": {
    "type": "jwt"
  },
  "lifecycle": {
    "installed": "/jira/installed",
    "uninstalled": "/jira/uninstalled"
  },
  "scopes": [
    "read",
    "act_as_user"
  ],
  "apiVersion": 1,
  "modules": {
    "generalPages": [
      {
        "url": "/jira",
        "key": "gP-moc-report",
        "location": "system.top.navigation.bar",
        "name": {
          "value": "MOC Report"
        }
      }
    ],
    "jiraReports": [
      {
        "url": "/jira?projectId={project.id}",
        "description": {
          "value": "This is an example report"
        },
        "reportCategory": "agile",
        "thumbnailUrl": "/assets/moc-logo.png",
        "name": {
          "value": "MOC Report"
        },
        "key": "jR-moc-report"
      }
    ],
    "jiraProjectPages": [
      {
        "key": "jPP-moc-report",
        "name": {
          "value": "MOC Report"
        },
        "url": "/jira?projectId={project.id}",
        "weight": 1
      }
    ]
  }
}

app/views/jira/index.haml
.ac_content
  %h3.title= t('moc.reports.time_report')

  = form_tag jira_show_path, :method => :get, :remote => true, :id => "query_form", :class => 'aui' do
    .field-group
      = label_tag :from, 'Choose dates'
      = date_field_tag :from , @form_params['from'], class: 'aui-date-picker date-picker'
      = date_field_tag :to , @form_params['to'], class: 'aui-date-picker date-picker'
      = link_to t("moc.periods.today"), "javascript:void(0)", class: 'set-date', data: {from: Date.today.strftime("%F"), to: Date.today.strftime("%F")}
      = link_to t("moc.periods.yesterday"), "javascript:void(0)", class: 'set-date', data: {from: (Date.today-1.day).strftime("%F"), to: (Date.today-1.day).strftime("%F")}
      = link_to t("moc.periods.this_week"), "javascript:void(0)", class: 'set-date', data: {from: Date.today.beginning_of_week.strftime("%F"), to: Date.today.strftime("%F")}
      = link_to t("moc.periods.this_month"), "javascript:void(0)", class: 'set-date', data: {from: Date.today.beginning_of_month.strftime("%F"), to: Date.today.strftime("%F")}
      = link_to t("moc.periods.last_month"), "javascript:void(0)", class: 'set-date', data: {from: (Date.today.beginning_of_month-1.month).strftime("%F"), to: (Date.today-1.month).end_of_month.strftime("%F")}
    .field-group
      - if params.key?('projectId')
        = hidden_field_tag('projects', params['projectId'])
      - else
        = label_tag :projects
        = select_tag 'projects', options_for_select(@form_params['projects']), multiple: true, class: 'aui-select2'
    .field-group
      = label_tag :issue_types, t("moc.labels.issue_types")
      = select_tag 'issue_types', options_for_select(@form_params['issue_types']), multiple: true, class: 'aui-select2'
    .field-group
      = label_tag :assignees
      = select_tag 'assignees', options_for_select(@form_params['assignees']), multiple: true, class: 'aui-select2'
    .field-group
      = label_tag :statuses
      = select_tag 'statuses', options_for_select(@form_params['statuses']), multiple: true, class: 'aui-select2'

    .field-group
      = label_tag :group_by, t("moc.labels.group_by")
      = select_tag 'group_by', options_for_select(@form_params['group_by']), multiple: true, class: 'aui-select2'
      = hidden_field_tag 'ordered_group_by'
    .field-group
      = label_tag :detail_by
      = select_tag 'detail_by', options_for_select(@form_params['detail_by']), class: 'aui-select2'
      -#= hidden_field_tag 'report_cache'

    .buttons-container
      .buttons
        = submit_tag 'Apply', :class => 'button submit', :id => 'apply'
        = link_to 'Clear', "javascript:void(0)", :class => 'cancel', :id => 'clear'

  #report

app/views/jira/show.js.erb
$('#report').html('<%= j render "report", report: @report %>');
// $('#data_store').data('report_data', @report.to_json);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JiraHello</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--<%= stylesheet_link_tag    '//aui-cdn.atlassian.com/aui-adg/6.0.9/css/aui.min.css', media: 'all' %>-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://romand.atlassian.net/atlassian-connect/all.js' %>

    <!--  AUI Core -->
    <!--<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>-->
    <!--<script src="//aui-cdn.atlassian.com/aui-adg/6.0.9/js/aui.min.js"></script>-->
    <link rel="stylesheet" href="//aui-cdn.atlassian.com/aui-adg/6.0.9/css/aui.min.css" media="all">

    <!-- AUI Experimental components -->
    <link rel="stylesheet" href="//aui-cdn.atlassian.com/aui-adg/6.0.9/css/aui-experimental.min.css" media="all">
    <!--<script src="//aui-cdn.atlassian.com/aui-adg/6.0.9/js/aui-experimental.min.js"></script>-->

    <!-- AUI Datepicker and Soy templates -->
    <!--<script src="//aui-cdn.atlassian.com/aui-adg/6.0.9/js/aui-datepicker.min.js"></script>-->
    <!--<script src="//aui-cdn.atlassian.com/aui-adg/6.0.9/js/aui-soy.min.js"></script>-->

  </head>

  <body>
    <%= yield %>
  </body>
</html>